Repository ManageIQ/manageiq-cross_repo-tests, pull requests merged in 2020-10, with the labels that each got.

#175 add provider list to readme
  README.md
Labels: documentation

#194 Move repo list into travis.yml as a comment
  .travis.yml
  README.md
Labels: documentation

#198 cleanup .travis.yml
  .travis.yml
Labels: developer

#201 Only run the master branch and not bot branches
  .travis.yml
Labels: enhancement
